[package]
name = "bluedb"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bluedb-client"
path = "src/bin/client.rs"


[dependencies]
sqlparser = "0.62.0"
rustyline = "18.0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
base64 = "0.22.1"
serde_json = "1.0.150"
anyhow = "1.0.103"
zerocopy = { version = "0.8", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
